"""
GBIFOccurrencesLib

This file was automatically generated by APIMATIC BETA v2.0 on 10/29/2015
"""

class EstablishmentMeansEnum(object):

    """Implementation of the 'EstablishmentMeans' enum.

    Vocabulary for the establishment means of a species. It is used mainly to
    characterize range distributions.

    Attributes:
        NATIVE: NATIVE
        INTRODUCED: INTRODUCED
        NATURALISED: NATURALISED
        INVASIVE: INVASIVE
        MANAGED: MANAGED
        UNCERTAIN: UNCERTAIN

    """

    NATIVE = "NATIVE"

    INTRODUCED = "INTRODUCED"

    NATURALISED = "NATURALISED"

    INVASIVE = "INVASIVE"

    MANAGED = "MANAGED"

    UNCERTAIN = "UNCERTAIN"


    @classmethod
    def to_string(cls, val):
        """Returns the string equivalent for the Enum.

        """
        for k,v in vars(cls).iteritems():
            if v==val:
                return k

    @classmethod
    def from_string(cls, str):
        """Creates an instance of the Enum from a given string.

        """
        return getattr(cls, str.upper(), None)