"""
GBIFOccurrencesLib

This file was automatically generated by APIMATIC BETA v2.0 on 10/29/2015
"""

class LayersObservationsEnum(object):

    """Implementation of the 'Layers_Observations' enum.

    Observation layers can take no year (&layer=OBS_NO_YEAR), before the 1900s
    (&layer=OBS_PRE_1900) or any decade after 1900.

    Attributes:
        OBS_NO_YEAR: OBS_NO_YEAR
        OBS_PRE_1900: OBS_PRE_1900
        OBS_1900_1910: OBS_1900_1910
        OBS_1910_1920: OBS_1910_1920
        OBS_1920_1930: OBS_1920_1930
        OBS_1930_1940: OBS_1930_1940
        OBS_1940_1950: OBS_1940_1950
        OBS_1950_1960: OBS_1950_1960
        OBS_1960_1970: OBS_1960_1970
        OBS_1970_1980: OBS_1970_1980
        OBS_1980_1990: OBS_1980_1990
        OBS_1990_2000: OBS_1990_2000
        OBS_2000_2010: OBS_2000_2010
        OBS_2010_2020: OBS_2010_2020

    """

    OBS_NO_YEAR = "OBS_NO_YEAR"

    OBS_PRE_1900 = "OBS_PRE_1900"

    OBS_1900_1910 = "OBS_1900_1910"

    OBS_1910_1920 = "OBS_1910_1920"

    OBS_1920_1930 = "OBS_1920_1930"

    OBS_1930_1940 = "OBS_1930_1940"

    OBS_1940_1950 = "OBS_1940_1950"

    OBS_1950_1960 = "OBS_1950_1960"

    OBS_1960_1970 = "OBS_1960_1970"

    OBS_1970_1980 = "OBS_1970_1980"

    OBS_1980_1990 = "OBS_1980_1990"

    OBS_1990_2000 = "OBS_1990_2000"

    OBS_2000_2010 = "OBS_2000_2010"

    OBS_2010_2020 = "OBS_2010_2020"


    @classmethod
    def to_string(cls, val):
        """Returns the string equivalent for the Enum.

        """
        for k,v in vars(cls).iteritems():
            if v==val:
                return k

    @classmethod
    def from_string(cls, str):
        """Creates an instance of the Enum from a given string.

        """
        return getattr(cls, str.upper(), None)