"""
GBIFOccurrencesLib

This file was automatically generated by APIMATIC BETA v2.0 on 10/29/2015
"""

class LayersOtherEnum(object):

    """Implementation of the 'Layers_Other' enum.

    Records where the basis of record is unknown, or something other than
    those above can take no year (&layer=OTH_NO_YEAR), before the 1900s
    (&layer=OTH_PRE_1900) or any decade after 1900.

    Attributes:
        OTH_NO_YEAR: OTH_NO_YEAR
        OTH_PRE_1900: OTH_PRE_1900
        OTH_1900_1910: OTH_1900_1910
        OTH_1910_1920: OTH_1910_1920
        OTH_1920_1930: OTH_1920_1930
        OTH_1930_1940: OTH_1930_1940
        OTH_1940_1950: OTH_1940_1950
        OTH_1950_1960: OTH_1950_1960
        OTH_1960_1970: OTH_1960_1970
        OTH_1970_1980: OTH_1970_1980
        OTH_1980_1990: OTH_1980_1990
        OTH_1990_2000: OTH_1990_2000
        OTH_2000_2010: OTH_2000_2010
        OTH_2010_2020: OTH_2010_2020

    """

    OTH_NO_YEAR = "OTH_NO_YEAR"

    OTH_PRE_1900 = "OTH_PRE_1900"

    OTH_1900_1910 = "OTH_1900_1910"

    OTH_1910_1920 = "OTH_1910_1920"

    OTH_1920_1930 = "OTH_1920_1930"

    OTH_1930_1940 = "OTH_1930_1940"

    OTH_1940_1950 = "OTH_1940_1950"

    OTH_1950_1960 = "OTH_1950_1960"

    OTH_1960_1970 = "OTH_1960_1970"

    OTH_1970_1980 = "OTH_1970_1980"

    OTH_1980_1990 = "OTH_1980_1990"

    OTH_1990_2000 = "OTH_1990_2000"

    OTH_2000_2010 = "OTH_2000_2010"

    OTH_2010_2020 = "OTH_2010_2020"


    @classmethod
    def to_string(cls, val):
        """Returns the string equivalent for the Enum.

        """
        for k,v in vars(cls).iteritems():
            if v==val:
                return k

    @classmethod
    def from_string(cls, str):
        """Creates an instance of the Enum from a given string.

        """
        return getattr(cls, str.upper(), None)