"""
   GBIFOccurrencesLib.Models.VerbatimOccurrence
 
   This file was automatically generated by APIMATIC BETA v2.0 on 10/29/2015
"""
from GBIFOccurrencesLib.APIHelper import APIHelper
from GBIFOccurrencesLib.Models.ContinentEnum import ContinentEnum

class VerbatimOccurrence(object):

    """Implementation of the 'VerbatimOccurrence' model.

    A verbatim occurrence record without any interpretation

    Attributes:
        key (string): key
        dataset_key (string): datasetKey
        publishing_org_key (string): publishingOrgKey
        publishing_country (string): publishingCountry
        protocol (string): protocol
        last_crawled (string): lastCrawled
        http_rs_tdwg_org_dwc_terms_day (int):
            http://rs.tdwg.org/dwc/terms/day
        http_rs_gbif_org_terms_1_0_gbif_id (int):
            http://rs.gbif.org/terms/1.0/gbifID
        http_rs_tdwg_org_dwc_terms_continent (ContinentEnum):
            http://rs.tdwg.org/dwc/terms/continent
        http_rs_tdwg_org_dwc_terms_country (string):
            http://rs.tdwg.org/dwc/terms/country
        http_rs_tdwg_org_dwc_terms_collection_code (string):
            http://rs.tdwg.org/dwc/terms/collectionCode
        http_rs_tdwg_org_dwc_terms_year (int):
            http://rs.tdwg.org/dwc/terms/year
        http_rs_tdwg_org_dwc_terms_locality (string):
            http://rs.tdwg.org/dwc/terms/locality
        http_rs_tdwg_org_dwc_terms_identified_by (string):
            http://rs.tdwg.org/dwc/terms/identifiedBy
        http_rs_tdwg_org_dwc_terms_verbatim_latitude (double):
            http://rs.tdwg.org/dwc/terms/verbatimLatitude
        http_rs_tdwg_org_dwc_terms_basis_of_record (string):
            http://rs.tdwg.org/dwc/terms/basisOfRecord
        http_rs_tdwg_org_dwc_terms_verbatim_longitude (double):
            http://rs.tdwg.org/dwc/terms/verbatimLongitude
        http_rs_tdwg_org_dwc_terms_catalog_number (int):
            http://rs.tdwg.org/dwc/terms/catalogNumber
        http_rs_tdwg_org_dwc_terms_month (int):
            http://rs.tdwg.org/dwc/terms/month
        http_rs_tdwg_org_dwc_terms_institution_code (string):
            http://rs.tdwg.org/dwc/terms/institutionCode
        http_rs_tdwg_org_dwc_terms_coordinate_precision (double):
            http://rs.tdwg.org/dwc/terms/coordinatePrecision
        http_rs_tdwg_org_dwc_terms_recorded_by (string):
            http://rs.tdwg.org/dwc/terms/recordedBy
        http_rs_tdwg_org_dwc_terms_scientific_name (string):
            http://rs.tdwg.org/dwc/terms/scientificName

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the VerbatimOccurrence class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    key -- string -- Sets the attribute key
                    datasetKey -- string -- Sets the attribute dataset_key
                    publishingOrgKey -- string -- Sets the attribute publishing_org_key
                    publishingCountry -- string -- Sets the attribute publishing_country
                    protocol -- string -- Sets the attribute protocol
                    lastCrawled -- string -- Sets the attribute last_crawled
                    http://rs.tdwg.org/dwc/terms/day -- int -- Sets the attribute http_rs_tdwg_org_dwc_terms_day
                    http://rs.gbif.org/terms/1.0/gbifID -- int -- Sets the attribute http_rs_gbif_org_terms_1_0_gbif_id
                    http://rs.tdwg.org/dwc/terms/continent -- ContinentEnum -- Sets the attribute http_rs_tdwg_org_dwc_terms_continent
                    http://rs.tdwg.org/dwc/terms/country -- string -- Sets the attribute http_rs_tdwg_org_dwc_terms_country
                    http://rs.tdwg.org/dwc/terms/collectionCode -- string -- Sets the attribute http_rs_tdwg_org_dwc_terms_collection_code
                    http://rs.tdwg.org/dwc/terms/year -- int -- Sets the attribute http_rs_tdwg_org_dwc_terms_year
                    http://rs.tdwg.org/dwc/terms/locality -- string -- Sets the attribute http_rs_tdwg_org_dwc_terms_locality
                    http://rs.tdwg.org/dwc/terms/identifiedBy -- string -- Sets the attribute http_rs_tdwg_org_dwc_terms_identified_by
                    http://rs.tdwg.org/dwc/terms/verbatimLatitude -- double -- Sets the attribute http_rs_tdwg_org_dwc_terms_verbatim_latitude
                    http://rs.tdwg.org/dwc/terms/basisOfRecord -- string -- Sets the attribute http_rs_tdwg_org_dwc_terms_basis_of_record
                    http://rs.tdwg.org/dwc/terms/verbatimLongitude -- double -- Sets the attribute http_rs_tdwg_org_dwc_terms_verbatim_longitude
                    http://rs.tdwg.org/dwc/terms/catalogNumber -- int -- Sets the attribute http_rs_tdwg_org_dwc_terms_catalog_number
                    http://rs.tdwg.org/dwc/terms/month -- int -- Sets the attribute http_rs_tdwg_org_dwc_terms_month
                    http://rs.tdwg.org/dwc/terms/institutionCode -- string -- Sets the attribute http_rs_tdwg_org_dwc_terms_institution_code
                    http://rs.tdwg.org/dwc/terms/coordinatePrecision -- double -- Sets the attribute http_rs_tdwg_org_dwc_terms_coordinate_precision
                    http://rs.tdwg.org/dwc/terms/recordedBy -- string -- Sets the attribute http_rs_tdwg_org_dwc_terms_recorded_by
                    http://rs.tdwg.org/dwc/terms/scientificName -- string -- Sets the attribute http_rs_tdwg_org_dwc_terms_scientific_name
        
        """
        # Set all of the parameters to their default values
        self.key = None
        self.dataset_key = None
        self.publishing_org_key = None
        self.publishing_country = None
        self.protocol = None
        self.last_crawled = None
        self.http_rs_tdwg_org_dwc_terms_day = None
        self.http_rs_gbif_org_terms_1_0_gbif_id = None
        self.http_rs_tdwg_org_dwc_terms_continent = None
        self.http_rs_tdwg_org_dwc_terms_country = None
        self.http_rs_tdwg_org_dwc_terms_collection_code = None
        self.http_rs_tdwg_org_dwc_terms_year = None
        self.http_rs_tdwg_org_dwc_terms_locality = None
        self.http_rs_tdwg_org_dwc_terms_identified_by = None
        self.http_rs_tdwg_org_dwc_terms_verbatim_latitude = None
        self.http_rs_tdwg_org_dwc_terms_basis_of_record = None
        self.http_rs_tdwg_org_dwc_terms_verbatim_longitude = None
        self.http_rs_tdwg_org_dwc_terms_catalog_number = None
        self.http_rs_tdwg_org_dwc_terms_month = None
        self.http_rs_tdwg_org_dwc_terms_institution_code = None
        self.http_rs_tdwg_org_dwc_terms_coordinate_precision = None
        self.http_rs_tdwg_org_dwc_terms_recorded_by = None
        self.http_rs_tdwg_org_dwc_terms_scientific_name = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "key": "key",
            "datasetKey": "dataset_key",
            "publishingOrgKey": "publishing_org_key",
            "publishingCountry": "publishing_country",
            "protocol": "protocol",
            "lastCrawled": "last_crawled",
            "http://rs.tdwg.org/dwc/terms/day": "http_rs_tdwg_org_dwc_terms_day",
            "http://rs.gbif.org/terms/1.0/gbifID": "http_rs_gbif_org_terms_1_0_gbif_id",
            "http://rs.tdwg.org/dwc/terms/continent": "http_rs_tdwg_org_dwc_terms_continent",
            "http://rs.tdwg.org/dwc/terms/country": "http_rs_tdwg_org_dwc_terms_country",
            "http://rs.tdwg.org/dwc/terms/collectionCode": "http_rs_tdwg_org_dwc_terms_collection_code",
            "http://rs.tdwg.org/dwc/terms/year": "http_rs_tdwg_org_dwc_terms_year",
            "http://rs.tdwg.org/dwc/terms/locality": "http_rs_tdwg_org_dwc_terms_locality",
            "http://rs.tdwg.org/dwc/terms/identifiedBy": "http_rs_tdwg_org_dwc_terms_identified_by",
            "http://rs.tdwg.org/dwc/terms/verbatimLatitude": "http_rs_tdwg_org_dwc_terms_verbatim_latitude",
            "http://rs.tdwg.org/dwc/terms/basisOfRecord": "http_rs_tdwg_org_dwc_terms_basis_of_record",
            "http://rs.tdwg.org/dwc/terms/verbatimLongitude": "http_rs_tdwg_org_dwc_terms_verbatim_longitude",
            "http://rs.tdwg.org/dwc/terms/catalogNumber": "http_rs_tdwg_org_dwc_terms_catalog_number",
            "http://rs.tdwg.org/dwc/terms/month": "http_rs_tdwg_org_dwc_terms_month",
            "http://rs.tdwg.org/dwc/terms/institutionCode": "http_rs_tdwg_org_dwc_terms_institution_code",
            "http://rs.tdwg.org/dwc/terms/coordinatePrecision": "http_rs_tdwg_org_dwc_terms_coordinate_precision",
            "http://rs.tdwg.org/dwc/terms/recordedBy": "http_rs_tdwg_org_dwc_terms_recorded_by",
            "http://rs.tdwg.org/dwc/terms/scientificName": "http_rs_tdwg_org_dwc_terms_scientific_name",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

            # Other objects also need to be initialised properly
            if "http://rs.tdwg.org/dwc/terms/continent" in kwargs:
                self.http_rs_tdwg_org_dwc_terms_continent = ContinentEnum.from_string(kwargs["http://rs.tdwg.org/dwc/terms/continent"])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "key": "key",
            "dataset_key": "datasetKey",
            "publishing_org_key": "publishingOrgKey",
            "publishing_country": "publishingCountry",
            "protocol": "protocol",
            "last_crawled": "lastCrawled",
            "http_rs_tdwg_org_dwc_terms_day": "http://rs.tdwg.org/dwc/terms/day",
            "http_rs_gbif_org_terms_1_0_gbif_id": "http://rs.gbif.org/terms/1.0/gbifID",
            "http_rs_tdwg_org_dwc_terms_continent": "http://rs.tdwg.org/dwc/terms/continent",
            "http_rs_tdwg_org_dwc_terms_country": "http://rs.tdwg.org/dwc/terms/country",
            "http_rs_tdwg_org_dwc_terms_collection_code": "http://rs.tdwg.org/dwc/terms/collectionCode",
            "http_rs_tdwg_org_dwc_terms_year": "http://rs.tdwg.org/dwc/terms/year",
            "http_rs_tdwg_org_dwc_terms_locality": "http://rs.tdwg.org/dwc/terms/locality",
            "http_rs_tdwg_org_dwc_terms_identified_by": "http://rs.tdwg.org/dwc/terms/identifiedBy",
            "http_rs_tdwg_org_dwc_terms_verbatim_latitude": "http://rs.tdwg.org/dwc/terms/verbatimLatitude",
            "http_rs_tdwg_org_dwc_terms_basis_of_record": "http://rs.tdwg.org/dwc/terms/basisOfRecord",
            "http_rs_tdwg_org_dwc_terms_verbatim_longitude": "http://rs.tdwg.org/dwc/terms/verbatimLongitude",
            "http_rs_tdwg_org_dwc_terms_catalog_number": "http://rs.tdwg.org/dwc/terms/catalogNumber",
            "http_rs_tdwg_org_dwc_terms_month": "http://rs.tdwg.org/dwc/terms/month",
            "http_rs_tdwg_org_dwc_terms_institution_code": "http://rs.tdwg.org/dwc/terms/institutionCode",
            "http_rs_tdwg_org_dwc_terms_coordinate_precision": "http://rs.tdwg.org/dwc/terms/coordinatePrecision",
            "http_rs_tdwg_org_dwc_terms_recorded_by": "http://rs.tdwg.org/dwc/terms/recordedBy",
            "http_rs_tdwg_org_dwc_terms_scientific_name": "http://rs.tdwg.org/dwc/terms/scientificName",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)