"""
   AtlasOfLivingAustraliaOccurrencesLib.Models.OccurrenceIndexedFieldsResponse
 
   This file was automatically generated by APIMATIC BETA v2.0 on 10/29/2015
"""
from AtlasOfLivingAustraliaOccurrencesLib.APIHelper import APIHelper

class OccurrenceIndexedFieldsResponse(object):

    """Implementation of the 'Occurrence_indexed_fields_Response' model.

    Occurrence_indexed_fields_Response

    Attributes:
        stored (bool): stored
        indexed (bool): indexed
        description (string): description
        data_type (string): dataType
        name (string): name

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the OccurrenceIndexedFieldsResponse class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    stored -- bool -- Sets the attribute stored
                    indexed -- bool -- Sets the attribute indexed
                    description -- string -- Sets the attribute description
                    dataType -- string -- Sets the attribute data_type
                    name -- string -- Sets the attribute name
        
        """
        # Set all of the parameters to their default values
        self.stored = None
        self.indexed = None
        self.description = None
        self.data_type = None
        self.name = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "stored": "stored",
            "indexed": "indexed",
            "description": "description",
            "dataType": "data_type",
            "name": "name",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "stored": "stored",
            "indexed": "indexed",
            "description": "description",
            "data_type": "dataType",
            "name": "name",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)