"""
AtlasOfLivingAustraliaOccurrencesLib

This file was automatically generated by APIMATIC BETA v2.0 on 10/29/2015
"""

class OccurrenceDownloadSourceTypeIdTypeEnum(object):

    """Implementation of the 'Occurrence_download_sourceTypeId_type' enum.

    A source type code for the download. This indicates which system requested
    the download

    Attributes:
        NAME: name
        ID: id

    """

    NAME = "name"

    ID = "id"


    @classmethod
    def to_string(cls, val):
        """Returns the string equivalent for the Enum.

        """
        for k,v in vars(cls).iteritems():
            if v==val:
                return k

    @classmethod
    def from_string(cls, str):
        """Creates an instance of the Enum from a given string.

        """
        return getattr(cls, str.upper(), None)