"""
   AtlasOfLivingAustraliaOccurrencesLib.Configuration

   This file was automatically generated by APIMATIC BETA v2.0 on 10/29/2015
"""

class Configuration :
    # The base Uri for API calls
    BASE_URI = "http://biocache.ala.org.au"


